### PR TITLE
Update applyFilters method to look for filter handler options

### PR DESCRIPTION
**Pull request by walshyb**
I built on @andremalkine 's [PR from 2015](https://github.com/coderhaoxin/gulp-file-include/pull/81) which he made in response to [an issue he created](https://github.com/coderhaoxin/gulp-file-include/issues/80) that asked for a feature to pass options into a filter handler in his gulpfile. 

His PR didn't pass the tests for filter options, but I modified his code slightly so that filter handler options are only passed if they are defined.

### CODE REVIEW

**Comment by walshyb** [comment]
Wondering if @coderhaoxin or someone else can take a look at this?

**Comment by coderhaoxin** [comment]
@walshyb can you add a test case for this ?

**Comment by walshyb** [comment]
Absolutely! I'm not sure I totally understand the structure of the tests, but I'll write one and if it's not in the right place, just let me know

**Comment by coderhaoxin** [comment]
`v2.0.0` published :)

**Comment by walshyb** [comment]
Awesome, thank you so much! :)

**Pull request merged**
