### PR TITLE
Fixed nested arguments and added tests for this case. Fixes #77

### LINKED ISSUE #77: Nested options are broken
It seems that nested options are broken at the moment and example from `examples` folder of the project doesn't work as well.

Here what I get after `gulp include` in `examples` folder:
```
[02:25:08] Using gulpfile d:\Projects\_my\gulp-file-include\example\gulpfile.js
[02:25:08] Starting 'include'...
[02:25:08] Finished 'include' after 14 ms

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Unexpected end of input
```

Probably the issue is related to this line:
```javascript
var args = /[^)"\']*["\']([^"\']*)["\'](,\s*({[\s\S]*?})){0,1}\s*/.exec(inst.args);
```
This regexp gets only one closed bracket and it results to not valid json that could not be parsed.

### PR DESCRIPTION
**Pull request by boccob**

### CODE REVIEW

**Comment by coderhaoxin** [comment]
rebase and land 09ce95b0b6c88c48eafe6ac509a7a61473efe5ad

**Comment by coderhaoxin** [comment]
thx

**Comment by coderhaoxin** [comment]
0.13.7 published cc @TrySound

**Comment by TrySound** [comment]
@boccob Thanks!

**Pull request closed without merging**
