### PR TITLE
for statement

### PR DESCRIPTION
**Pull request by alexliu1987**

### CODE REVIEW

**Comment by coderhaoxin** [comment]
👍 

@alexliu1987 can you add some test cases? :)

**Comment by alexliu1987** [comment]
done. but why The Travis CI build failed?

**Comment by coderhaoxin** [comment]
also cc @TrySound for some feedback!

**Comment by coderhaoxin** [comment]
`v0.14.0` published

**Comment by coderhaoxin** [comment]
land 0446e5217781748d417040ce89fca8b9a8fab145

**Pull request closed without merging**
